algoritmo "contas3numeros"
var
N1,N2,N3,V1,V2:real
inicio
Escreval("Me dê 3 números e farei algumas contas com eles")
Escreval("Me dê o primeiro:")
Leia(N1)
Escreval("Me dê o segundo:")
Leia(N2)
Escreval("Me dê o terceiro:")
Leia (N3)
V1 <- N1+N2
V2 <- N2+N3
Escreval("A soma do primeiro com o segundo é:", V1," que ao ser multiplicado pela soma do segundo pelo terceiro que é ",V2, " Da", V1*V2)

fimalgoritmo